[mobile]:  An impressive experience of developing a landing page for pc and mobile
bricktile/blog pull request #4
Opened 2020-02-17 14:48 UTC by xiaojingzhao

[mobile]:  An impressive experience of developing a landing page for pc and mobile

2020-02-20 14:48 UTC, ShiKaiWi requested changes

2020-02-20 14:48 UTC, ShiKaiWi commented on mobile/移动端问题.md
> +因为涉及到屏幕自适应的问题。我就使用了 rem 作为自适应方案。这是我第一次使用 rem 作为自适应方案，遇到了一些问题。
第一个句号似乎不太合适，下面的句号都请斟酌一下。

2020-02-20 14:48 UTC, ShiKaiWi commented on mobile/移动端问题.md
> +1. 用 js 获取屏幕大小，手：动设置根元素字体大小。
自己 check 一下，似乎文章质量不够。

2020-02-20 15:00 UTC, hehex9 commented on mobile/移动端问题.md
> +1. 用 js 获取屏幕大小，手：动设置根元素字体大小。
> 自己 check 一下，似乎文章质量不够。

笑死

2020-03-03 15:20 UTC, woshixixi commented on mobile/移动端问题.md
> +1. 用 js 获取屏幕大小，手：动设置根元素字体大小。
挺好的啊 感觉 😂

2020-03-18 08:18 UTC, merged